DROP TABLE IF EXISTS PRODUCT_MODEL, ITEM, CLIENT, EVALUATION, SALE;

CREATE TABLE PRODUCT_MODEL (
    Id INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE,
    Description TEXT
);

CREATE TABLE ITEM (
    Series_number INT PRIMARY KEY,
    Value INT NOT NULL CHECK (Value > 0),
    Id_model INT NOT NULL,
    FOREIGN KEY (Id_model) REFERENCES PRODUCT_MODEL (Id)
);